name: Deploy [GH-Pages]
on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Only deploy on pushes to the master branch
    needs: build-web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Clear existing content
        run: |
          rm -rf ./*
      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: .
      - name: Add and commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Deploy content to gh-pages"
      - name: Push changes
        run: |
          git push origin gh-pages