name: Kotlin Multiplatform CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Android
        run: ./gradlew composeApp:assembleDebug

#      - name: Build iOS
#        run: |
#          sudo xcode-select -s /Applications/Xcode_13.2.1.app
#          ./gradlew linkDebugFrameworkIos

#      - name: Build Desktop
#        run: ./gradlew composeApp:run

#      - name: Build Web
#        run: ./gradlew wasmJsBrowserRun -t --quiet

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/debug/*.apk

#      - name: Upload iOS Framework
#        uses: actions/upload-artifact@v4
#        with:
#          name: ios-framework
#          path: iosApp/build/bin/ios/debugFramework/*.framework
#
#      - name: Upload Web Build
#        uses: actions/upload-artifact@v4
#        with:
#          name: web-build
#          path: jsApp/build/distributions/

#  merge-develop-to-master:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#        with:
#          ref: develop
#      - name: Set up Git configuration
#        run: |
#          git config user.name "GitHub Actions Bot"
#          git config user.email "<>"
#      - name: Merge develop to master
#        run: |
#          git fetch origin master
#          git checkout master
#          git merge develop --no-ff -m "Automatically merge develop into master"
#          git push origin master