name: KMM CI/CD / Deploy to Pages

on:
  push:
    branches:
      - master
      - develop

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-common:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Test Common
        run: ./gradlew composeApp:cleanDesktopTest :composeApp:desktopTest --tests "TestDelegate"

  build-android:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Android
        run: ./gradlew composeApp:assembleDebug

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/debug/*.apk

  build-web:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Web
        run: ./gradlew wasmJsBrowserDistribution

      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: composeApp/build/dist/wasmJs/productionExecutable

  build-server-to-docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: steven147
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Server App Jar
        run: ./gradlew buildFatJar

      - name: Build Docker Image
        run: ./gradlew buildImage

      - name: Publish Docker Image
        run: ./gradlew publishImage

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker steven147/adaption-server
            docker stop $(docker ps -aqf "ancestor=steven147/adaption-server") || true
            docker rm $(docker ps -aqf "ancestor=steven147/adaption-server") || true
            docker run -d -p 5000:5000 steven147/adaption-server

  # Single deploy job since we're just deploying
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Only deploy on pushes to the master branch
    needs: build-web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Clear existing content
        run: |
          rm -rf ./*
      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: .
      - name: Add and commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Deploy content to gh-pages"
      - name: Push changes
        run: |
          git push origin gh-pages